### ISSUE TITLE
Build fails with kipoiseq master

### ISSUE THREAD

**Issue by lauradmartens** [kipoi/website#104]
I changed the kipoiseq installation in `.circleci/config.yml` from GitHub to pip
`pip install git+ssh://git@github.com/kipoi/kipoiseq.git` to `pip install kipoiseq`
https://github.com/kipoi/website/blob/fe3d72e1608468da4d5322a05ce8c42f83927e9a/.circleci/config.yml#L23

Once the error is fixed in kipoiseq, we should change it back.

**Comment by haimasree** [comment]
Fixed by [this commit](https://github.com/kipoi/website/commit/22f0f9cd313f24a23aca1f7a92b7cbd4d51ccf25).
More input required from kipoiseq developers. Details are [here](https://github.com/kipoi/kipoiseq/issues/95)
