### ISSUE TITLE
Add a model list button 

### ISSUE THREAD

**Issue by Avsecz** [kipoi/website#20]
It would be nice if the user could choose between viewing all the models (just as listed with list_model()) and between viewing the grouped models. 

Toggle could be implemented either via some toggle button, or by adding a button "Model List" to the top:
![image](https://user-images.githubusercontent.com/10011161/35771055-f025b2dc-0926-11e8-8c68-259007eaacfe.png)

**Comment by zupan** [comment]
@Avsecz is this still relevant?

**Comment by Avsecz** [comment]
15% maybe, 85% no :)

**Comment by Avsecz** [comment]
ok. let's close this. It would just clutter the interface and if people want to search by protein names etc, they can do it in the pandas dataframe returned by `kipoi.list_models()`.
