### ISSUE TITLE
Cisco site block

### ISSUE THREAD

**Issue by Avsecz** [kipoi/website#65]

**Comment by Nico-NYGC** [comment]
Hi,
The site is blocked here and it seems to be coming from a Cisco filter. The info I have is:
ACType 0
Block Type security
Bundle ID 907945
Domain Tagging -
Host malware.opendns.com
IP Address (...)
Org ID 2416689
Origin ID 134185341
Prefs -
Query url=kipoi.org&server=nyc15&prefs=&tagging=&nref
Server nyc15
Time 2018-03-14 13:52:48.068333405 +0000 UTC m=+42850.846421245

**Comment by Avsecz** [comment]
Hm. Do you get it as well if you visit
- kipoi.org/about/
- kipoi.org/docs/
- kipoi.org/groups
?

**Comment by Nico-NYGC** [comment]
Yes, same problem. Don't worry too much if it's just me, I suppose it will be fixed sometimes soon. I may chack back in a few days!

**Comment by Avsecz** [comment]
Do you also get it of you visit: http://time.com?

**Comment by Nico-NYGC** [comment]
No, that's fine. Kipoi is the first time I have that error.

**Comment by Avsecz** [comment]
Ok. @nzupan do you have any idea what could go wrong?

**Comment by Nico-NYGC** [comment]
It now works. Apparently, this kind of issue can happen with brand new domains. Thanks

**Comment by Avsecz** [comment]
Great! I'll close the issue. Feel free to re-open it if it occurs again. We'll try to setup https soon.
